import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='flex flex-col mx-auto max-w-[600px]'>
        <div className='flex w-full justify-between'>
          <Link href='/' className='text-black'>
            plify
          </Link>
          <Link href='/list' className='text-black'>
            List
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
