import type { Metadata } from 'next';
import './globals.css';
import TopNav from './components/Common/layouts/TopNav';
import Providers from './Providers';
import DesktopTopNav from './components/Common/layouts/DesktopTopNav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className='flex flex-col min-h-screen'>
        <Providers>
          <DesktopTopNav />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
