import type { Metadata } from 'next';
import '../ui/globals.css';
import Providers from './components/Providers/Providers';
import DesktopTopNav from './components/Common/layouts/DesktopTopNav';
import ThemeProvider from './components/Providers/ThemeProvider';
import PlayerWrapper from './components/Player/PlayerWrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='flex flex-col min-h-screen bg-white dark:bg-black text-black dark:text-white'>
        <ThemeProvider>
          <Providers>
            {/* 상단 sticky: DesktopTopNav */}
            <div className='sticky top-0 z-50 backdrop-blur-md'>
              <DesktopTopNav />
            </div>
            <main className='flex-grow bg-white dark:bg-black text-black dark:text-white'>
              {children}
            </main>
            {/* 하단 sticky: PlayerWrapper */}
            <div className='sticky bottom-0 z-50  backdrop-blur-md'>
              <PlayerWrapper />
            </div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
